### ISSUE TITLE
build artifacts could be placed in build/ directory

### ISSUE THREAD

**Issue by SanjitRaman** [LangProc/langproc-cw#12]
Adding this feature would prevent pollution of the src/ folder.

**Comment by Fiwo735** [comment]
Sounds like a good change, especially as most students are going to have the repo hierarchy open on a side at all times, so that should reduce clutter. Could you please open a pull request modifying the `Makefile` (and anything else that's needed - _coverage_ might require some attention) @SanjitRaman?
